name: forex-web
services:
  web:
    build: .
    container_name: forex-web
    volumes:
      - ./src:/var/www/html
    networks:
      - forex-network

  nginx:
    image: nginx:alpine
    container_name: forex-nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - forex-network

networks:
  forex-network:
    driver: bridge